import type { CollectionConfig } from "./collection-manager";
import type { Row } from "@/lib/admin-db";

const str = (row: Row, key: string) => String(row[key] ?? "");

export const projectsCollection: CollectionConfig = {
  table: "projects",
  title: "Projects",
  description: "Case studies shown on the site. Unpublished entries stay private.",
  primaryLabel: (row) => str(row, "title"),
  secondaryLabel: (row) => `${str(row, "category")} · /${str(row, "slug")}`,
  defaults: {
    title: "",
    slug: "",
    subtitle: "",
    category: "",
    summary: "",
    problem: "",
    solution: "",
    implementation: "",
    outcome: "",
    tech_stack: [],
    architecture_steps: [],
    features: [],
    highlights: [],
    cover_url: "",
    demo_url: "",
    github_url: "",
    start_date: null,
    end_date: null,
    featured: false,
    published: true,
    sort_order: 0,
  },
  fields: [
    { name: "title", label: "Title", type: "text" },
    { name: "slug", label: "Slug", type: "text", placeholder: "smart-verification-system" },
    { name: "subtitle", label: "Subtitle", type: "text", full: true },
    { name: "category", label: "Category", type: "text", placeholder: "Blockchain" },
    { name: "sort_order", label: "Sort order", type: "number" },
    { name: "summary", label: "Summary", type: "textarea", rows: 3 },
    { name: "problem", label: "Problem", type: "textarea" },
    { name: "solution", label: "Solution", type: "textarea" },
    { name: "implementation", label: "Implementation", type: "textarea" },
    { name: "outcome", label: "Outcome", type: "textarea" },
    { name: "tech_stack", label: "Tech stack", type: "list" },
    { name: "architecture_steps", label: "Architecture steps", type: "list" },
    { name: "features", label: "Key features", type: "list" },
    { name: "highlights", label: "Highlights", type: "list" },
    { name: "cover_url", label: "Cover image", type: "media" },
    { name: "demo_url", label: "Live demo URL", type: "text" },
    { name: "github_url", label: "GitHub URL", type: "text" },
    { name: "start_date", label: "Start date", type: "date" },
    { name: "end_date", label: "End date", type: "date" },
    { name: "featured", label: "Featured on home", type: "switch" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const experiencesCollection: CollectionConfig = {
  table: "experiences",
  title: "Experience",
  description: "Roles, internships, leadership and volunteering.",
  primaryLabel: (row) => str(row, "title"),
  secondaryLabel: (row) => str(row, "organization"),
  defaults: {
    title: "",
    organization: "",
    kind: "Experience",
    location: "",
    start_date: null,
    end_date: null,
    description: "",
    bullets: [],
    published: true,
    sort_order: 0,
  },
  fields: [
    { name: "title", label: "Role title", type: "text" },
    { name: "organization", label: "Organization", type: "text" },
    { name: "kind", label: "Type", type: "text", placeholder: "Internship / Volunteering" },
    { name: "location", label: "Location", type: "text" },
    { name: "start_date", label: "Start date", type: "date" },
    { name: "end_date", label: "End date", type: "date" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "bullets", label: "Highlights", type: "list" },
    { name: "sort_order", label: "Sort order", type: "number" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const educationCollection: CollectionConfig = {
  table: "education",
  title: "Education",
  description: "Degrees, schools and academic highlights.",
  primaryLabel: (row) => `${str(row, "degree")} ${str(row, "field")}`.trim(),
  secondaryLabel: (row) => str(row, "institution"),
  defaults: {
    degree: "",
    field: "",
    institution: "",
    location: "",
    start_date: null,
    end_date: null,
    description: "",
    highlights: [],
    published: true,
    sort_order: 0,
  },
  fields: [
    { name: "degree", label: "Degree", type: "text" },
    { name: "field", label: "Field of study", type: "text" },
    { name: "institution", label: "Institution", type: "text" },
    { name: "location", label: "Location", type: "text" },
    { name: "start_date", label: "Start date", type: "date" },
    { name: "end_date", label: "End date", type: "date" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "highlights", label: "Highlights", type: "list" },
    { name: "sort_order", label: "Sort order", type: "number" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const achievementsCollection: CollectionConfig = {
  table: "achievements",
  title: "Achievements",
  description: "Certifications, awards and recognitions.",
  primaryLabel: (row) => str(row, "title"),
  secondaryLabel: (row) => str(row, "issuer"),
  defaults: {
    title: "",
    issuer: "",
    description: "",
    date: null,
    url: "",
    published: true,
    sort_order: 0,
  },
  fields: [
    { name: "title", label: "Title", type: "text" },
    { name: "issuer", label: "Issuer", type: "text" },
    { name: "date", label: "Date", type: "date" },
    { name: "url", label: "Credential URL", type: "text" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "sort_order", label: "Sort order", type: "number" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const statsCollection: CollectionConfig = {
  table: "stats",
  title: "Hero stats",
  description: "The metric strip under the hero. Icon names come from Lucide.",
  primaryLabel: (row) => `${str(row, "value")} — ${str(row, "label")}`,
  defaults: { label: "", value: "", icon: "Sparkles", published: true, sort_order: 0 },
  fields: [
    { name: "value", label: "Value", type: "text" },
    { name: "label", label: "Label", type: "text" },
    { name: "icon", label: "Lucide icon name", type: "text", placeholder: "Sparkles" },
    { name: "sort_order", label: "Sort order", type: "number" },
    { name: "published", label: "Published", type: "switch" },
  ],
};

export const skillCategoriesCollection: CollectionConfig = {
  table: "skill_categories",
  title: "Skill categories",
  description: "Groups shown in the skills grid.",
  primaryLabel: (row) => str(row, "name"),
  secondaryLabel: (row) => `Icon: ${str(row, "icon")}`,
  defaults: { name: "", icon: "Code2", published: true, sort_order: 0 },
  fields: [
    { name: "name", label: "Category name", type: "text" },
    { name: "icon", label: "Lucide icon name", type: "text", placeholder: "Code2" },
    { name: "sort_order", label: "Sort order", type: "number" },
    { name: "published", label: "Published", type: "switch" },
  ],
};
